modLoader = "javafml"
loaderVersion = "[40,)"
license = "Apache 2.0+ARR"

[[mods]]
modId = "better_loading_screen"
version = "${version}"
displayName = "Better Loading Screen"
authors = "shedaniel"
description = '''
A mod to improve the loading screen.
'''
logoFile = "icon.png"

[[dependencies.better_loading_screen]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_loading_screen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
